### PR TITLE
chore: add leading underscore to examples directory

### PR DESCRIPTION
**Pull request by alex1989hu**
Unfortunately the dependency `github.com/eaigner/dkim` is no longer available

As a temporary solution we need to put leading underscore to let Go recursively ignore it

Signed-off-by: Alex Szakaly <alex.szakaly@gmail.com>

**Note**:
This is a workaround until final solution is accepted.

Possible long term solution can be found here: <https://github.com/chrj/smtpd/pull/12>

### CODE REVIEW

**Comment by alex1989hu** [comment]
FYI: force pushed but no success: not able to trigger `Build`

**Comment by decke** [comment]
Yeah that solution looks reasonable and a lot less intrusive than #12

Thanks!

**Review by JonathonReinhart — APPROVED** [review]
This looks great to me.

As a reference:

> Directory and file names that begin with "." or "_" are ignored by the go tool, as are directories named "testdata".

https://pkg.go.dev/cmd/go#hdr-Package_lists_and_patterns

**Comment by chrj** [comment]
@alex1989hu @JonathonReinhart thanks for the investigation. Tagged this as `v0.3.1`.

**Pull request merged**
